skip_tags: true

build_script:
  - Build.bat

test: off

artifacts:
  - path: 'bin\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: UWLHsXH6B9+FIAZ4HCbSnvKBAi1LHvmA3JLtLfjUccKRIUwS1VgutW5j9UkizRBn
  artifact: /.*\.nupkg/